### ISSUE TITLE
basic ReadMe Usage example not working

### ISSUE THREAD

**Issue by Naor-Tedgi** [DanielJDufour/location-extractor#3]
using 

Linux Mint 18.1 64 bit
Python 2.7.12

ruining installation 

**main.py** 
`from location_extractor import extract_locations
text = "I arrived in New York on January 4, 1937"
locations = extract_locations(text)
`

**error** 
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from location_extractor import extract_locations
  File "/usr/local/lib/python2.7/dist-packages/location_extractor/__init__.py", line 4, in <module>
    from broth import Broth
  File "/usr/local/lib/python2.7/dist-packages/broth/__init__.py", line 1, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'`

**Comment by Naor-Tedgi** [comment]
never mind find a solution 

**pip install --upgrade beautifulsoup4
pip install --upgrade html5lib**

**Comment by DanielJDufour** [comment]
@Naor-Tedgi , glad to hear it! and thank you!
